spring:
  profiles:
    active: dev #  激活开发环境
---
server:
  port: 8001 # 端口号
mybatis:
  config-localtion: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.asyt.springcloud.entity  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product #服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
eureka:
  client:
    register-with-eureka: true # 服务注册开关
    fetch-registry: true  # 服务发现开关
    service-url: # 注册到哪一个Eureka Server 服务注册中心，多个中间用逗号分割
      #defaultZone: http://localhost:6001/eureka  # 单机版
      #集群版 Eureka 服务注册中心
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名称
    prefer-ip-address: true # 访问路径可以显示IP地址
---
server:
  port: 8001 # 端口号
mybatis:
  config-localtion: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.asyt.springcloud.entity  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-product #服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
eureka:
  client:
    register-with-eureka: true # 服务注册开关
    fetch-registry: true  # 服务发现开关
    service-url: # 注册到哪一个Eureka Server 服务注册中心，多个中间用逗号分割
      #defaultZone: http://localhost:6001/eureka  # 单机版
      #集群版 Eureka 服务注册中心
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名称
    prefer-ip-address: true # 访问路径可以显示IP地址